algo: "DQN"
env: "ALE/Pong-v5"
total_timesteps: 1000000
learning_rate: 0.00025
buffer_size: 500000
learning_starts: 100000
batch_size: 256
exploration_fraction: 0.4
exploration_final_eps: 0.01
train_log_interval: 100

# Network optimization
gamma: 0.99
target_update_interval: 1000
gradient_steps: 4
train_freq: 4
frame_stack: 4

# Preprocessing
scale_rewards: true
normalize_frames: true
terminal_on_life_loss: true

# Workshop and visualization settings
viz_interval: 25000
video_interval: 100000
video_length: 400
checkpoint_interval: 100000
demo_mode: false 